# Generated by Django 3.2.4 on 2021-06-24 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/default.jpeg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 13, 44, 39, 421795, tzinfo=utc)),
        ),
    ]
